<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,700,900|Roboto+Mono:300,400,500"> 
<link rel="stylesheet" href="{{asset('site/fonts/icomoon/style.css')}}">
<link rel="stylesheet" href="{{asset('site/css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('site/css/magnific-popup.css')}}">
<link rel="stylesheet" href="{{asset('site/css/jquery-ui.css')}}">
<link rel="stylesheet" href="{{asset('site/css/owl.carousel.min.css')}}">
<link rel="stylesheet" href="{{asset('site/css/owl.theme.default.min.css')}}">
<link rel="stylesheet" href="{{asset('site/css/bootstrap-datepicker.css')}}">
<link rel="stylesheet" href="{{asset('site/css/mediaelementplayer.css')}}">
<link rel="stylesheet" href="{{asset('site/css/animate.css')}}">
<link rel="stylesheet" href="{{asset('site/fonts/flaticon/font/flaticon.css')}}">
<link rel="stylesheet" href="{{asset('site/css/fl-bigmug-line.css')}}">      
<link rel="stylesheet" href="{{asset('site/css/aos.css')}}">
<link rel="stylesheet" href="{{asset('site/css/style.css?ver=3')}}">    
